/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sunny
 */
public class ManageCustomersWorkArena extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomersWorkArena
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    CustomerDirectory cd;
    public ManageCustomersWorkArena(JPanel userProcessContainer , EcoSystem ecosystem) {
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        custoTable = new javax.swing.JTable();
        btnHome = new javax.swing.JButton();
        lblCustomers = new javax.swing.JLabel();
        listCustomers = new javax.swing.JComboBox<>();
        txtUCustUpdate = new javax.swing.JTextField();
        txtUpwdCusto = new javax.swing.JTextField();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        custoTable1 = new javax.swing.JTable();
        bgdimg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 28)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Customer  Directory");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 39, 390, 50));

        custoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Password"
            }
        ));
        jScrollPane1.setViewportView(custoTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 107, 389, 141));

        btnHome.setText("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 90, 40));

        lblCustomers.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        lblCustomers.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomers.setText("Customers");
        add(lblCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 97, -1));

        listCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCustomersActionPerformed(evt);
            }
        });
        add(listCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 118, -1));

        txtUCustUpdate.setEditable(false);
        add(txtUCustUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, 118, -1));
        add(txtUpwdCusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 118, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 90, 30));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 493, 80, 30));

        lblUsername.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("Username:");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        lblPassword.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password:");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 80, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        custoTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Password"
            }
        ));
        jScrollPane2.setViewportView(custoTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 107, 389, 141));

        bgdimg.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bgdimg.setIcon(new javax.swing.ImageIcon("D:\\Study\\Northeastern University\\INFO 5100_AED\\Assignments\\Assignment Images\\Assignment 5\\connecting_with_customers_822x606.jpg")); // NOI18N
        jPanel1.add(bgdimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 0, 850, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel) custoTable.getModel();
        int selectedRow = custoTable.getSelectedRow();
        String userName = (String) df.getValueAt(selectedRow, 0);
        cd = ecosystem.getCustomerDirectory();
        df.removeRow(selectedRow);
        //populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
            crdLyt.show(userProcessContainer,"Sysadmin");
    }//GEN-LAST:event_btnHomeActionPerformed

    private void listCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCustomersActionPerformed
        // TODO add your handling code here:
        String custo = (String) listCustomers.getSelectedItem();
        cd = ecosystem.getCustomerDirectory();
        ArrayList<Customer> restos = cd.getCustomerList();
        for(Customer r: restos)
        {
            if(r.getCustomerName().equals(custo))
            {
               txtUCustUpdate.setText(r.getUa().getUsername());
               txtUpwdCusto.setText(r.getUa().getPassword());
            }
        }
    }//GEN-LAST:event_listCustomersActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String custo = (String) listCustomers.getSelectedItem();
        cd = ecosystem.getCustomerDirectory();
        ArrayList<Customer> restos = cd.getCustomerList();
        for(Customer r: restos)
        {
            if(r.getCustomerName().equals(custo))
            {
               r.getUa().setPassword(txtUpwdCusto.getText());
            }
            
        }
        JOptionPane.showMessageDialog(this, "Password Updated");
        populateTable();
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgdimg;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTable custoTable;
    private javax.swing.JTable custoTable1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCustomers;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JComboBox<String> listCustomers;
    private javax.swing.JTextField txtUCustUpdate;
    private javax.swing.JTextField txtUpwdCusto;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
         cd = ecosystem.getCustomerDirectory();
        ArrayList<Customer> custos = cd.getCustomerList();
        DefaultTableModel df = (DefaultTableModel) custoTable.getModel();
        df.setRowCount(0);
        DefaultComboBoxModel dc = new DefaultComboBoxModel();
        
        for(Customer c: custos)
        {
            String[] row = {c.getCustomerName(),c.getUa().getPassword()};
            df.addRow(row);
            dc.addElement(c.getCustomerName());
        }
        custoTable.setModel(df);
        listCustomers.setModel(dc);
    }
}
