/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;

import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Vehicle;
import model.VehicleHistory;

/**
 *
 * @author Saketh
 */
public class CreateJPanel extends javax.swing.JPanel {
    
    VehicleHistory carDetailsHistory ;

    /** Creates new form CreateJPanel */
    public CreateJPanel(VehicleHistory carDetailsHistory ) {
        initComponents();
        this.carDetailsHistory = carDetailsHistory;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblmfgName = new javax.swing.JLabel();
        lblmfgYear = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        txtmfgName = new javax.swing.JTextField();
        txtmfgYear = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        noChecked = new javax.swing.JRadioButton();
        yesChecked = new javax.swing.JRadioButton();
        lblCarAvailability2 = new javax.swing.JLabel();
        lblYearOfManufacturing1 = new javax.swing.JLabel();
        jComboNumSeats = new javax.swing.JComboBox<>();
        lblmfgCompany = new javax.swing.JLabel();
        txtmfgCompany = new javax.swing.JTextField();
        lblmainCert = new javax.swing.JLabel();
        txtserialNum = new javax.swing.JTextField();
        lblserialNum = new javax.swing.JLabel();
        txtmainCert = new javax.swing.JTextField();
        lblvidNum = new javax.swing.JLabel();
        txtmodelNum = new javax.swing.JTextField();
        lblmodelNum = new javax.swing.JLabel();
        txtvIDNum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(190, 253, 251));
        setPreferredSize(new java.awt.Dimension(600, 600));

        lblmfgName.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblmfgName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblmfgName.setText("Model Name :");

        lblmfgYear.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblmfgYear.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblmfgYear.setText("Manufactured Year:");

        lblLocation.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblLocation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblLocation.setText("Location :");

        txtmfgName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.gray));
        txtmfgName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmfgNameActionPerformed(evt);
            }
        });

        txtmfgYear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.gray));

        txtLocation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.gray));

        btnSave.setFont(new java.awt.Font("Mongolian Baiti", 3, 12)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        noChecked.setText("No");
        noChecked.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.cyan, java.awt.Color.black, java.awt.Color.cyan));
        noChecked.setPreferredSize(new java.awt.Dimension(40, 20));
        noChecked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noCheckedActionPerformed(evt);
            }
        });

        yesChecked.setText("Yes");
        yesChecked.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.cyan, java.awt.Color.black, java.awt.Color.cyan));
        yesChecked.setMinimumSize(new java.awt.Dimension(40, 20));
        yesChecked.setPreferredSize(new java.awt.Dimension(40, 20));
        yesChecked.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesCheckedActionPerformed(evt);
            }
        });

        lblCarAvailability2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblCarAvailability2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCarAvailability2.setText("Availability :");

        lblYearOfManufacturing1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblYearOfManufacturing1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblYearOfManufacturing1.setText("Number of Seats :");

        jComboNumSeats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "4", "6" }));
        jComboNumSeats.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.darkGray, java.awt.Color.black, java.awt.Color.lightGray));
        jComboNumSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboNumSeatsActionPerformed(evt);
            }
        });

        lblmfgCompany.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblmfgCompany.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblmfgCompany.setText("Manufacturer Company :");

        txtmfgCompany.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.gray));
        txtmfgCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmfgCompanyActionPerformed(evt);
            }
        });

        lblmainCert.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblmainCert.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblmainCert.setText("Maintance Certificate :");

        txtserialNum.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.gray));

        lblserialNum.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblserialNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblserialNum.setText("Serial Number :");

        txtmainCert.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.gray));

        lblvidNum.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblvidNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblvidNum.setText("Vehicle Number :");

        txtmodelNum.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.gray));

        lblmodelNum.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblmodelNum.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblmodelNum.setText("Model Number :");

        txtvIDNum.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.black, java.awt.Color.gray, java.awt.Color.black, java.awt.Color.gray));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(180, 180, 180)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(262, 262, 262))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(104, 104, 104)
                                    .addComponent(lblCarAvailability2))
                                .addComponent(lblYearOfManufacturing1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(70, 70, 70)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(42, 42, 42)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(yesChecked, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(36, 36, 36)
                                            .addComponent(noChecked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jComboNumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(57, 57, 57))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtserialNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtmainCert, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtvIDNum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtmodelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtmfgYear, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtmfgName, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtmfgCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addContainerGap()))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblserialNum)
                                .addComponent(lblmainCert))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblmfgName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblmfgCompany, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblmfgYear, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblLocation, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(lblvidNum, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblmodelNum, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(418, 418, 418)))))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {noChecked, yesChecked});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblmfgCompany)
                        .addGap(28, 28, 28)
                        .addComponent(lblmfgName)
                        .addGap(28, 28, 28)
                        .addComponent(lblmfgYear)
                        .addGap(28, 28, 28)
                        .addComponent(lblLocation)
                        .addGap(27, 27, 27)
                        .addComponent(lblserialNum)
                        .addGap(27, 27, 27)
                        .addComponent(lblmainCert)
                        .addGap(25, 25, 25)
                        .addComponent(lblvidNum)
                        .addGap(28, 28, 28)
                        .addComponent(lblmodelNum, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(lblCarAvailability2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtmfgCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtmfgName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtmfgYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtserialNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtmainCert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtvIDNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtmodelNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yesChecked, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noChecked, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboNumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblYearOfManufacturing1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {noChecked, yesChecked});

    }// </editor-fold>//GEN-END:initComponents

    private void txtmfgNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmfgNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmfgNameActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        if(txtserialNum.getText().isEmpty()||txtmainCert.getText().isEmpty()||txtmodelNum.getText().isEmpty()||txtvIDNum.getText().isEmpty()
                ||txtmfgCompany.getText().isEmpty()||txtmfgName.getText().isEmpty()||txtmfgYear.getText().isEmpty()
                ||txtLocation.getText().isEmpty()||yesChecked.getText().isEmpty()||noChecked.getText().isEmpty()
                ||jComboNumSeats.getSelectedIndex()==0)
        {
	JOptionPane.showMessageDialog(this,"Values are missing." );
        }
        else
        {
        String mfgCompany = txtmfgCompany.getText();
        String mfgName = txtmfgName.getText();
        String mfgYear = txtmfgYear.getText();
        String location = txtLocation.getText();
        String serialNum = txtserialNum.getText();
        String vIDNum = txtvIDNum.getText();
        String modelNum = txtmodelNum.getText();
        String mainCert = txtmainCert.getText();
        //int numSeats = Integer.parseInt(txtNumSeats.getText());
        
        //JOptionPane.showMessageDialog(this, numSeats);
        //String carAvailability = txtCarAvailability.getText();
        
        String selectedValue = jComboNumSeats.getSelectedItem().toString();
        
        //jComboNumSeats.addItem(addValue);  //get the value of textField and add it to JComboBox
        
        //JOptionPane.showMessageDialog(this, selectedValue);
        
        Vehicle carDetails = carDetailsHistory.addNewCarDetails();
        
        carDetails.setMfgCompany(mfgCompany);
        carDetails.setmfgName(mfgName);
        carDetails.setYearOfManufacturing(mfgYear);
        carDetails.setLocation(location);
        carDetails.setNumSeats(Integer.parseInt(selectedValue));
        carDetails.setSerialNum(serialNum);
        carDetails.setModelNum(modelNum);
        carDetails.setvIDNum(vIDNum);
        carDetails.setMainCert(mainCert);
        
        if(yesChecked.isSelected()){
          //  JOptionPane.showMessageDialog(this, yesChecked.getText());
            carDetails.setCarAvailability(yesChecked.getText());
        }else {
          //   JOptionPane.showMessageDialog(this, noChecked.getText());
             carDetails.setCarAvailability(noChecked.getText());
        }
//        if(yesChecked1.isSelected()){
//        carDetails.setmainCert(yesChecked1.getText());
//        }else {
//        //JOptionPane.showMessageDialog(this, "For Maintenance Certificate as nothing is selected its considered to be 'NO' ");
//        carDetails.setmainCert(noChecked.getText());
//        }


        JOptionPane.showMessageDialog(this, "Information Succesfully Recorded");
        
        //clearing the text after the car details are saved
        txtmfgCompany.setText("");
        txtmfgName.setText("");
        txtmfgYear.setText("");
        txtLocation.setText("");
        txtserialNum.setText("");
        txtmainCert.setText("");
        txtvIDNum.setText("");
        txtmodelNum.setText("");
        yesChecked.setSelected(false);
        noChecked.setSelected(false);
      //  jComboNumSeats.setAction(a);
//        yesChecked1.setSelected(false);
//        noChecked1.setSelected(false);
        //txtNumSeats.setText("");
        //txtCarAvailability.setText("");

        
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void noCheckedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noCheckedActionPerformed
        // TODO add your handling code here: 
       if (noChecked.isSelected())
            yesChecked.setSelected(false);
    }//GEN-LAST:event_noCheckedActionPerformed

    private void jComboNumSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboNumSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboNumSeatsActionPerformed

    private void txtmfgCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmfgCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmfgCompanyActionPerformed

    private void yesCheckedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesCheckedActionPerformed
        // TODO add your handling code here:
        if (yesChecked.isSelected())
            noChecked.setSelected(false);      
        
    }//GEN-LAST:event_yesCheckedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> jComboNumSeats;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCarAvailability2;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblYearOfManufacturing1;
    private javax.swing.JLabel lblmainCert;
    private javax.swing.JLabel lblmfgCompany;
    private javax.swing.JLabel lblmfgName;
    private javax.swing.JLabel lblmfgYear;
    private javax.swing.JLabel lblmodelNum;
    private javax.swing.JLabel lblserialNum;
    private javax.swing.JLabel lblvidNum;
    private javax.swing.JRadioButton noChecked;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtmainCert;
    private javax.swing.JTextField txtmfgCompany;
    private javax.swing.JTextField txtmfgName;
    private javax.swing.JTextField txtmfgYear;
    private javax.swing.JTextField txtmodelNum;
    private javax.swing.JTextField txtserialNum;
    private javax.swing.JTextField txtvIDNum;
    private javax.swing.JRadioButton yesChecked;
    // End of variables declaration//GEN-END:variables

}
