/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.createNewUser;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.DB4OUtil.DB4OUtil;
import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.Role.AdminRole;
import Business.Role.CustomerRole;
import Business.Role.DeliverManRole;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.MainJFrame;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author sunny
 */
public class createLogin extends javax.swing.JPanel {

    /**
     * Creates new form createLogin
     */
    EcoSystem ecosystem;
    JPanel userProcessContainer;
    RestaurantDirectory rd;
    Restaurant restaurant;
    UserAccount ua;
    Customer customer;
    DeliveryMan delivery;
    CustomerDirectory cd;
    DeliveryManDirectory dd;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public createLogin(JPanel userProcessContainer,EcoSystem ecosystem) {
       this.ecosystem = ecosystem;
       this.userProcessContainer = userProcessContainer;
       
       if(ecosystem.getRestaurantDirectory() == null)
           ecosystem.setRestaurantDirectory(new RestaurantDirectory());
       if(ecosystem.getCustomerDirectory() == null)
           ecosystem.setCustomerDirectory(new CustomerDirectory());
       if(ecosystem.getDeliveryManDirectory() == null)
           ecosystem.setDeliveryManDirectory(new DeliveryManDirectory());
       initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblusername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblrole = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblConfirmPassword = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtUName = new javax.swing.JTextField();
        txtPasswd = new javax.swing.JTextField();
        txtCnfrmPwd = new javax.swing.JTextField();
        roleCmb = new javax.swing.JComboBox<>();
        btnCreateUser = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        lblRestaurantName = new javax.swing.JLabel();
        txtRestaurantName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblusername.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblusername.setForeground(new java.awt.Color(255, 255, 255));
        lblusername.setText("Username:");
        add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 76, -1));

        lblPassword.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password:");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 92, -1));

        lblrole.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblrole.setForeground(new java.awt.Color(255, 255, 255));
        lblrole.setText("Role:");
        add(lblrole, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        lblName.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        lblConfirmPassword.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmPassword.setText("Confirm Password:");
        add(lblConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 103, -1));
        add(txtUName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 103, -1));
        add(txtPasswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 103, -1));
        add(txtCnfrmPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 103, -1));

        roleCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Restaurant Admin", "Customer", "Delivery Man" }));
        roleCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleCmbActionPerformed(evt);
            }
        });
        add(roleCmb, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 129, -1));

        btnCreateUser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnCreateUser.setText("CREATE USER");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });
        add(btnCreateUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 150, 40));

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitle.setText("Create New User");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 27, 199, 32));

        btnHome.setText("Back");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 13, 70, 30));

        lblRestaurantName.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        lblRestaurantName.setForeground(new java.awt.Color(255, 255, 255));
        lblRestaurantName.setText("Restaurant Name:");
        add(lblRestaurantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 110, -1));

        txtRestaurantName.setEditable(false);
        add(txtRestaurantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 129, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Study\\Northeastern University\\INFO 5100_AED\\Assignments\\Assignment Images\\Assignment 5\\users3_add.png")); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        // TODO add your handling code here:
        UserAccountDirectory usersList = ecosystem.getUserAccountDirectory();
        String role = (String) roleCmb.getSelectedItem();
        Employee employee = new Employee();
        employee.setName(txtName.getText());
        boolean userDoNotExists = true;
        ArrayList<UserAccount> users = usersList.getUserAccountList();
        for(UserAccount ua : users)
        {
            if(ua.getUsername().equals(txtUName.getText()))
                userDoNotExists = false;
        }
        
        if(userDoNotExists)
        {
        if(txtPasswd.getText().equals(txtCnfrmPwd.getText()))
        {
            switch (role) {
                case "Restaurant Admin":
                    usersList.createUserAccount(txtUName.getText(),txtPasswd.getText(), employee, new AdminRole());
                    ua = usersList.getUserAccount(txtUName.getText());
                     restaurant = new Restaurant(ua);
                    restaurant.setName(txtRestaurantName.getText());
                    rd = ecosystem.getRestaurantDirectory();
                    rd.addResto(restaurant);
                    ecosystem.setRestaurantDirectory(rd);
                    break;
                case "Customer":
                    usersList.createUserAccount(txtUName.getText(),txtPasswd.getText(), employee, new CustomerRole());
                    ua = usersList.getUserAccount(txtUName.getText());
                    customer = new Customer(ua);
                    cd = ecosystem.getCustomerDirectory();
                    cd.addCusto(customer);
                    break;
                case "Delivery Man":
                    usersList.createUserAccount(txtUName.getText(),txtPasswd.getText(), employee, new DeliverManRole());
                    ua = usersList.getUserAccount(txtUName.getText());
                    delivery = new DeliveryMan(ua);
                    dd = ecosystem.getDeliveryManDirectory();
                    dd.addDelivery(delivery);
                    break;
                default:
                    break;
            }
        
            JOptionPane.showMessageDialog(this,"User created");
            txtUName.setText("");
            txtPasswd.setText("");
            txtCnfrmPwd.setText("");
            txtName.setText("");
            txtRestaurantName.setText("");
        }
        
        else
            JOptionPane.showMessageDialog(this,"Password and confirm password does not match");
        }
        else
            JOptionPane.showMessageDialog(this,"UserName already exist");
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void roleCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleCmbActionPerformed
        // TODO add your handling code here:
        if(roleCmb.getSelectedItem().equals("Restaurant Admin"))
            txtRestaurantName.setEnabled(true);
            txtRestaurantName.setEditable(true);
    }//GEN-LAST:event_roleCmbActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
        crdLyt.show(userProcessContainer,"Sysadmin");
        
    }//GEN-LAST:event_btnHomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRestaurantName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblrole;
    private javax.swing.JLabel lblusername;
    private javax.swing.JComboBox<String> roleCmb;
    private javax.swing.JTextField txtCnfrmPwd;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPasswd;
    private javax.swing.JTextField txtRestaurantName;
    private javax.swing.JTextField txtUName;
    // End of variables declaration//GEN-END:variables
}
