/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface;

import Persona.Community;
import Persona.Person;
import Persona.PersonDirectory;
import Persona.House;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sunny
 */
public class PersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonJPanel
     */
    
    PersonDirectory personDir;
    
    public PersonJPanel(PersonDirectory personDir) {
        initComponents();
        
        this.personDir = personDir;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblPersonName = new javax.swing.JLabel();
        txtPersonName = new javax.swing.JTextField();
        txtPersonID = new javax.swing.JTextField();
        lblPersonID = new javax.swing.JLabel();
        txtPersonAge = new javax.swing.JTextField();
        lblPersonAge = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        txtHouseNumber = new javax.swing.JTextField();
        lblHouseNumber = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        btnSave = new javax.swing.JButton();
        txtStreetName = new javax.swing.JTextField();
        lblStreetName = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblCity = new javax.swing.JLabel();
        txtCommunity = new javax.swing.JTextField();
        lblCommunity = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPerson = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtState = new javax.swing.JTextField();
        lblState = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1536, 864));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setBackground(new java.awt.Color(153, 255, 255));
        lblTitle.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ENTER PERSON DETAILS");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 28, 1500, 40));

        lblPersonName.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        lblPersonName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPersonName.setText("Person Name :");
        add(lblPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 124, 100, 30));
        add(txtPersonName, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 129, 200, 25));
        add(txtPersonID, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 177, 200, 25));

        lblPersonID.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        lblPersonID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPersonID.setText("Person Id :");
        add(lblPersonID, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 172, 100, 30));
        add(txtPersonAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 225, 200, 25));

        lblPersonAge.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        lblPersonAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPersonAge.setText("Person Age :");
        add(lblPersonAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 220, 100, 30));

        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });
        add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 273, 200, 25));

        lblPhoneNumber.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        lblPhoneNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPhoneNumber.setText("Phone Number :");
        add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 268, 100, 30));
        add(txtHouseNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 316, 200, 25));

        lblHouseNumber.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        lblHouseNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblHouseNumber.setText("House Number :");
        add(lblHouseNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 316, 100, 30));

        lblGender.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        lblGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblGender.setText("Gender :");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 100, 30));

        rbtnMale.setText("MALE");
        rbtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMaleActionPerformed(evt);
            }
        });
        add(rbtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 320, -1, -1));

        rbtnFemale.setText("FEMALE");
        rbtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFemaleActionPerformed(evt);
            }
        });
        add(rbtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 320, -1, -1));

        btnSave.setText("CREATE PERSON");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 396, 190, 33));
        add(txtStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 120, 200, 25));

        lblStreetName.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        lblStreetName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblStreetName.setText("Street Name :");
        add(lblStreetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 100, 30));
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 170, 200, 25));

        lblCity.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        lblCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCity.setText("City :");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 170, 100, 30));
        add(txtCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 220, 200, 25));

        lblCommunity.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        lblCommunity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCommunity.setText("Community :");
        add(lblCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, 100, 30));

        tblPerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "PersonID", "Name", "Age", "Gender", "Phone Number", "House Number", "Street Name", "City", "State", "Community"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPerson);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 1380, 200));

        btnView.setText("VIEW");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 723, 140, 40));

        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 723, 140, 40));

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 723, 140, 40));

        btnSearch.setText("SEARCH");
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 723, 140, 40));
        add(txtState, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 270, 200, 25));

        lblState.setFont(new java.awt.Font("Dubai Medium", 0, 14)); // NOI18N
        lblState.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblState.setText("State :");
        add(lblState, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, 100, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
           if(txtCity.getText().isEmpty()||txtCommunity.getText().isEmpty()||txtHouseNumber.getText().isEmpty()||txtPersonAge.getText().isEmpty()
                ||txtPersonID.getText().isEmpty()||txtPersonName.getText().isEmpty()||txtPhoneNumber.getText().isEmpty()
                ||txtStreetName.getText().isEmpty()||rbtnMale.getText().isEmpty()||rbtnFemale.getText().isEmpty()
                ||txtState.getText().isEmpty())
        {
	JOptionPane.showMessageDialog(this,"Values are missing." );
        }
           else
           {
       // Reference:  double respiratoryRate = Double.parseDouble(txtRespiratoryRate.getText());
        String Name = txtPersonName.getText();
        int Age = Integer.parseInt(txtPersonAge.getText());
        long Phone = Long.parseLong(txtPhoneNumber.getText());
        int ID = Integer.parseInt(txtPersonID.getText());
        String StreetName = txtStreetName.getText();
        String City = txtCity.getText();
        int HouseNumber = Integer.parseInt(txtHouseNumber.getText());
        String communityname = txtCommunity.getText();
        String State = txtState.getText();
        
        
          Person person = personDir.addNewPerson();
          House house = new House();
          
          
        
        person.setName(Name);
        person.setAge(Integer.parseInt(txtPersonAge.getText()));
        person.setPhone(Long.parseLong(txtPhoneNumber.getText()));
//        person.setGender(Gender);
//        person.setID();
        house.setCity(City);
        house.setHouseNumber(Integer.parseInt(txtHouseNumber.getText()));
        house.setState(State);
        house.setStreetName(StreetName);
        
        person.setHouse(house);
        String Gender;
        if(rbtnMale.isSelected()){
          //  JOptionPane.showMessageDialog(this, yesChecked.getText());
            Gender = rbtnMale.getText();
            person.setGender(Gender);
        }else {
          //   JOptionPane.showMessageDialog(this, noChecked.getText());
          Gender = rbtnFemale.getText();   
          person.setGender(Gender);
        }

        JOptionPane.showMessageDialog(this, "Information Succesfully Recorded");
        
        DefaultTableModel model = (DefaultTableModel) tblPerson.getModel();
        model.addRow(new Object[]{ID, Name, Age, Gender, Phone, HouseNumber, StreetName, City, State } );
        
        //clearing the text after the car details are saved
        txtCity.setText("");
        txtCommunity.setText("");
        txtHouseNumber.setText("");
        txtPersonAge.setText("");
        txtPersonID.setText("");
        txtPersonName.setText("");
        txtPhoneNumber.setText("");
        txtState.setText("");
        txtStreetName.setText("");
        rbtnMale.setSelected(false);
        rbtnFemale.setSelected(false);
        
        
        
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void rbtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFemaleActionPerformed
        // TODO add your handling code here:
        if (rbtnFemale.isSelected())
            rbtnMale.setSelected(false);
    }//GEN-LAST:event_rbtnFemaleActionPerformed

    private void rbtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMaleActionPerformed
        // TODO add your handling code here:
        if (rbtnMale.isSelected())
            rbtnFemale.setSelected(false);
    }//GEN-LAST:event_rbtnMaleActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int SelectedRowIndex = tblPerson.getSelectedRow();
       
       if(SelectedRowIndex  < 0) {
           JOptionPane.showMessageDialog(this, "Select a Row, which you wish to remove");
           return;
       }
       
       DefaultTableModel model = (DefaultTableModel) tblPerson.getModel();
       Person selectedPerson = (Person) model.getValueAt(SelectedRowIndex, 0);
        
       personDir.deletepersonDetails(selectedPerson);
       
       JOptionPane.showMessageDialog(this, "Selected Row succesfully deleted!");
       
       populateTable();
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblPerson.getSelectedRow();
        
        if(selectedRowIndex<0) {
            JOptionPane.showMessageDialog(this, "Please select a row to view");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblPerson.getModel();
        
        Person selectedPerson = (Person) model.getValueAt(selectedRowIndex, 0);
        House selectedHouse = (House) model.getValueAt(selectedRowIndex, 0);
//      for (Person person : personDir.getPersonDir()){
//            House house = person.getHouse();
        
        txtPersonName.setText(selectedPerson.getName());
        txtPersonAge.setText(String.valueOf(selectedPerson.getAge()));
        txtPersonID.setText(String.valueOf(selectedPerson.getID()));
        txtPhoneNumber.setText(String.valueOf(selectedPerson.getPhone()));
        if(selectedPerson.getGender().equals("Yes")) {
            rbtnMale.setSelected(true);
        } else {
            rbtnFemale.setSelected(true);
        }
        
        txtHouseNumber.setText(String.valueOf(selectedHouse.getHouseNumber()));
        txtStreetName.setText(String.valueOf(selectedHouse.getStreetName()));
        txtCity.setText(selectedHouse.getCity());
        txtState.setText(selectedHouse.getState());
             
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHouseNumber;
    private javax.swing.JLabel lblPersonAge;
    private javax.swing.JLabel lblPersonID;
    private javax.swing.JLabel lblPersonName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblStreetName;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JTable tblPerson;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtHouseNumber;
    private javax.swing.JTextField txtPersonAge;
    private javax.swing.JTextField txtPersonID;
    private javax.swing.JTextField txtPersonName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtState;
    private javax.swing.JTextField txtStreetName;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model = (DefaultTableModel) tblPerson.getModel();
        model.setRowCount(0);
        
        for (Person person : personDir.getPersonDir()){
            House house = person.getHouse();
            Object[] row = new Object[9];
            row[0]= person;
            row[1]= person.getName();
            row[2]= person.getAge();
            row[3]= person.getGender();
            row[4]= person.getPhone();
            row[5]= house.getHouseNumber();
            row[6]= house.getStreetName();
            row[7]= house.getCity();
            row[8]= house.getState();
           // 
            
            
            model.addRow(row);
            
        }
    }
}
    
