/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainJFrame;

import Model.MainUser;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import static javax.swing.JFileChooser.APPROVE_OPTION;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;


/**
 *
 * @author sunny
 */
public class createJPanel extends javax.swing.JPanel {

    /**
     * Creates new form createJPanel
     */
    MainUser user;
    
    
    public createJPanel(MainUser user) {
        initComponents();
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbtitle = new javax.swing.JLabel();
        btnname = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        btnaddress = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        btndob = new javax.swing.JLabel();
        btntelephone = new javax.swing.JLabel();
        txttelephone = new javax.swing.JTextField();
        btnfaxnum = new javax.swing.JLabel();
        txtfaxnum = new javax.swing.JTextField();
        btnemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        btnssn = new javax.swing.JLabel();
        txtssn = new javax.swing.JTextField();
        btnmedical = new javax.swing.JLabel();
        txtmedical = new javax.swing.JTextField();
        btnhealth = new javax.swing.JLabel();
        txthealth = new javax.swing.JTextField();
        btnaccount = new javax.swing.JLabel();
        txtaccount = new javax.swing.JTextField();
        btnlicense = new javax.swing.JLabel();
        txtlicense = new javax.swing.JTextField();
        btnserialnumber = new javax.swing.JLabel();
        txtserialnumber = new javax.swing.JTextField();
        btndeviceid = new javax.swing.JLabel();
        txtdeviceid = new javax.swing.JTextField();
        btnlinkedin = new javax.swing.JLabel();
        txtlinkedin = new javax.swing.JTextField();
        btnip = new javax.swing.JLabel();
        txtip = new javax.swing.JTextField();
        btnuniqueid = new javax.swing.JLabel();
        txtuniqueid = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        lblimage = new javax.swing.JLabel();
        btnimgbrowse = new javax.swing.JButton();
        image_path_label = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setPreferredSize(new java.awt.Dimension(1000, 1000));

        lbtitle.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        lbtitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbtitle.setText("Create Information");
        lbtitle.setToolTipText("");

        btnname.setText("Name:");

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });

        btnaddress.setText("Address:");

        btndob.setText("Date of Birth");

        btntelephone.setText("Telephone");

        txttelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelephoneActionPerformed(evt);
            }
        });
        txttelephone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelephoneKeyPressed(evt);
            }
        });

        btnfaxnum.setText("FAX number");

        txtfaxnum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfaxnumKeyPressed(evt);
            }
        });

        btnemail.setText("Email address");

        btnssn.setText("Social Security Number");

        txtssn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtssnKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtssnKeyTyped(evt);
            }
        });

        btnmedical.setText("Medical Record");

        txtmedical.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtmedicalKeyPressed(evt);
            }
        });

        btnhealth.setText("Healthplan Beneficiary");

        txthealth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txthealthKeyPressed(evt);
            }
        });

        btnaccount.setText("Bank Account Number");

        txtaccount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtaccountKeyPressed(evt);
            }
        });

        btnlicense.setText("Certificate/ License");

        txtlicense.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtlicenseKeyPressed(evt);
            }
        });

        btnserialnumber.setText("Vehicle Registration");

        txtserialnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtserialnumberKeyPressed(evt);
            }
        });

        btndeviceid.setText("Device number");

        txtdeviceid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdeviceidKeyPressed(evt);
            }
        });

        btnlinkedin.setText("Linkedin");

        btnip.setText("Internet protocol");

        btnuniqueid.setText("Unique ID");

        txtuniqueid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuniqueidKeyPressed(evt);
            }
        });

        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        lblimage.setText("Image");

        btnimgbrowse.setText("Browse //");
        btnimgbrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimgbrowseActionPerformed(evt);
            }
        });

        image_path_label.setText("Unique ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnemail, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnname, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnfaxnum, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(txtfaxnum, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnssn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnmedical, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(txtmedical, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnhealth, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(txthealth, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(txtaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnlicense, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(txtlicense, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnserialnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(txtserialnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btndeviceid, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(txtdeviceid, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btntelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btndob, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(51, 51, 51)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txttelephone, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnlinkedin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnip, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnuniqueid, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtuniqueid, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtip, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtlinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(36, 36, 36)
                        .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnimgbrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(70, 70, 70))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(image_path_label, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(187, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(304, 304, 304))))
            .addGroup(layout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbtitle)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnname)
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnaddress)
                            .addComponent(txtaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btndob)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btntelephone)
                            .addComponent(txttelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnfaxnum)
                            .addComponent(txtfaxnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnemail)
                            .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnssn)
                            .addComponent(txtssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnmedical)
                            .addComponent(txtmedical, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnhealth)
                            .addComponent(txthealth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnaccount)
                            .addComponent(txtaccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblimage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnimgbrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(image_path_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlicense)
                    .addComponent(txtlicense, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnserialnumber)
                    .addComponent(txtserialnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndeviceid)
                    .addComponent(txtdeviceid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlinkedin)
                    .addComponent(txtlinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnip)
                    .addComponent(txtip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnuniqueid)
                    .addComponent(txtuniqueid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txttelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelephoneActionPerformed
        // TODO add your handling code here:
        
        createJPanel createpanel = new createJPanel(user);
        
    }//GEN-LAST:event_txttelephoneActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed

        user.setName(txtname.getText());
        user.setAddress(txtaddress.getText());
        user.setDob(jDateChooser1.getDate());
        user.setTelephone(Long.parseLong(txttelephone.getText()));
        user.setFax(Long.parseLong(txtfaxnum.getText()));
        user.setEmail(txtemail.getText());
        user.setSsn(Integer.parseInt(txtssn.getText()));
        user.setMedical(txtmedical.getText());
        user.setHealth(Integer.parseInt(txthealth.getText()));
        user.setAccount(Long.parseLong(txtaccount.getText()));
        user.setLicense(Integer.parseInt(txtlicense.getText()));
        user.setSerialnumber(txtserialnumber.getText());
        user.setDeviceid(Integer.parseInt(txtdeviceid.getText()));
        user.setLinkedin(txtlinkedin.getText());
        user.setIp(txtip.getText());
       // user.setBiometric(txtbiometric.getText());
        user.setUniqueid(txtuniqueid.getText());
       
        JOptionPane.showMessageDialog(this, "The Information is recorded");

        // TODO add your handling code here:
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtssnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtssnKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtssnKeyTyped

    private void txtssnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtssnKeyPressed
        // TODO add your handling code here:
        String SSN=txtssn.getText();
        //get length of a string
        int length =SSN.length();
        
        char c = evt.getKeyChar();
        
        //Check for number 0-9
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<9){
                //editable true
                txtssn.setEditable(true);
            }else{
                //not editable for length more than 10 digits 
                txtssn.setEditable(false);
                
            }
        }else{
            //allow  keys 'back space' and 'delete'
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                //allow editable
                txtssn.setEditable(true);
                
            }else{
                txtssn.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtssnKeyPressed

    private void txttelephoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelephoneKeyPressed
        // TODO add your handling code here:
        String tele=txttelephone.getText();
        //get length of a string
        int length =tele.length();
        
        char c = evt.getKeyChar();
        
        //Check for number 0-9
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<10){
                //editable true
                txttelephone.setEditable(true);
            }else{
                //not editable for length more than 10 digits 
                txttelephone.setEditable(false);
                
            }
        }else{
            //allow  keys 'back space' and 'delete'
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                //allow editable
                txttelephone.setEditable(true);
                
            }else{
                txttelephone.setEditable(false);
            }
                
            
            
        }
    }//GEN-LAST:event_txttelephoneKeyPressed

    private void txtaccountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaccountKeyPressed
        // TODO add your handling code here: 
        String bank=txtaccount.getText();
        //get length of a string
        int length =bank.length();
        
        char c = evt.getKeyChar();
        
        //Check for number 0-9
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<12){
                //editable true
                txtaccount.setEditable(true);
            }else{
                //not editable for length more than 10 digits 
                txtaccount.setEditable(false);
                
            }
        }else{
            //allow  keys 'back space' and 'delete'
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                //allow editable
                txtaccount.setEditable(true);
                
            }else{
                txtaccount.setEditable(false);
            }
                
            
            
        }
        
    }//GEN-LAST:event_txtaccountKeyPressed

    private void btnimgbrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimgbrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();
        
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg","jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
        
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION){
            File selectedImageFile = browseImageFile.getSelectedFile();
             String selectedImagePath = selectedImageFile.getAbsolutePath();
             user.setImg_path(selectedImagePath);
             image_path_label.setText(selectedImagePath);
//             JOptionPane.showMessageDialog(null, selectedImagePath);
             //Display image on the Jlabel
//             ImageIcon ii = new ImageIcon(selectedImagePath);
             //Resize image to fit jlabel
//             Image image= ii.getImage().getScaledInstance(lblimage.getWidth(),lblimage.getHeight(),Image.SCALE_SMOOTH);
//                     lblimage.setIcon(new ImageIcon(image));  
        }
    }//GEN-LAST:event_btnimgbrowseActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtuniqueidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuniqueidKeyPressed
        // TODO add your handling code here:
         String SSN=txtuniqueid.getText();
        //get length of a string
        int length =SSN.length();
        
        char c = evt.getKeyChar();
        
        //Check for number 0-9
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<6){
                //editable true
                txtuniqueid.setEditable(true);
            }else{
                //not editable for length more than 10 digits 
                txtuniqueid.setEditable(false);
                
            }
        }else{
            //allow  keys 'back space' and 'delete'
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                //allow editable
                txtuniqueid.setEditable(true);
                
            }else{
                txtuniqueid.setEditable(false);
            }
        }
        
        
    }//GEN-LAST:event_txtuniqueidKeyPressed

    private void txtdeviceidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdeviceidKeyPressed
        // TODO add your handling code here:
         String SSN=txtdeviceid.getText();
        //get length of a string
        int length =SSN.length();
        
        char c = evt.getKeyChar();
        
        //Check for number 0-9
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<16){
                //editable true
                txtdeviceid.setEditable(true);
            }else{
                //not editable for length more than 10 digits 
                txtdeviceid.setEditable(false);
                
            }
        }else{
            //allow  keys 'back space' and 'delete'
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                //allow editable
                txtdeviceid.setEditable(true);
                
            }else{
                txtdeviceid.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtdeviceidKeyPressed

    private void txtserialnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtserialnumberKeyPressed
        // TODO add your handling code here: 
        String SSN=txtserialnumber.getText();
        //get length of a string
        int length =SSN.length();
        
        char c = evt.getKeyChar();
        
        //Check for number 0-9
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<16){
                //editable true
                txtserialnumber.setEditable(true);
            }else{
                //not editable for length more than 10 digits 
                txtserialnumber.setEditable(false);
                
            }
        }else{
            //allow  keys 'back space' and 'delete'
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                //allow editable
                txtserialnumber.setEditable(true);
                
            }else{
                txtserialnumber.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtserialnumberKeyPressed

    private void txtlicenseKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtlicenseKeyPressed
        // TODO add your handling code here:
         String SSN=txtlicense.getText();
        //get length of a string
        int length =SSN.length();
        
        char c = evt.getKeyChar();
        
        //Check for number 0-9
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<16){
                //editable true
                txtlicense.setEditable(true);
            }else{
                //not editable for length more than 10 digits 
                txtlicense.setEditable(false);
                
            }
        }else{
            //allow  keys 'back space' and 'delete'
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                //allow editable
                txtlicense.setEditable(true);
                
            }else{
                txtlicense.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtlicenseKeyPressed

    private void txthealthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthealthKeyPressed
        // TODO add your handling code here:
         String SSN=txthealth.getText();
        //get length of a string
        int length =SSN.length();
        
        char c = evt.getKeyChar();
        
        //Check for number 0-9
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<16){
                //editable true
                txthealth.setEditable(true);
            }else{
                //not editable for length more than 10 digits 
                txthealth.setEditable(false);
                
            }
        }else{
            //allow  keys 'back space' and 'delete'
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                //allow editable
                txthealth.setEditable(true);
                
            }else{
                txthealth.setEditable(false);
            }
        }
    }//GEN-LAST:event_txthealthKeyPressed

    private void txtmedicalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmedicalKeyPressed
        // TODO add your handling code here:
         String SSN=txtmedical.getText();
        //get length of a string
        int length =SSN.length();
        
        char c = evt.getKeyChar();
        
        //Check for number 0-9
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<16){
                //editable true
                txtmedical.setEditable(true);
            }else{
                //not editable for length more than 10 digits 
                txtmedical.setEditable(false);
                
            }
        }else{
            //allow  keys 'back space' and 'delete'
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                //allow editable
                txtmedical.setEditable(true);
                
            }else{
                txtmedical.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtmedicalKeyPressed

    private void txtfaxnumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfaxnumKeyPressed
        // TODO add your handling code here:
         String SSN=txtfaxnum.getText();
        //get length of a string
        int length =SSN.length();
        
        char c = evt.getKeyChar();
        
        //Check for number 0-9
        
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            if (length<10){
                //editable true
                txtfaxnum.setEditable(true);
            }else{
                //not editable for length more than 10 digits 
                txtfaxnum.setEditable(false);
                
            }
        }else{
            //allow  keys 'back space' and 'delete'
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                //allow editable
                txtfaxnum.setEditable(true);
                
            }else{
                txtfaxnum.setEditable(false);
            }
        }
    }//GEN-LAST:event_txtfaxnumKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnaccount;
    private javax.swing.JLabel btnaddress;
    private javax.swing.JLabel btndeviceid;
    private javax.swing.JLabel btndob;
    private javax.swing.JLabel btnemail;
    private javax.swing.JLabel btnfaxnum;
    private javax.swing.JLabel btnhealth;
    private javax.swing.JButton btnimgbrowse;
    private javax.swing.JLabel btnip;
    private javax.swing.JLabel btnlicense;
    private javax.swing.JLabel btnlinkedin;
    private javax.swing.JLabel btnmedical;
    private javax.swing.JLabel btnname;
    private javax.swing.JButton btnsave;
    private javax.swing.JLabel btnserialnumber;
    private javax.swing.JLabel btnssn;
    private javax.swing.JLabel btntelephone;
    private javax.swing.JLabel btnuniqueid;
    private javax.swing.JLabel image_path_label;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel lblimage;
    private javax.swing.JLabel lbtitle;
    private javax.swing.JTextField txtaccount;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtdeviceid;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfaxnum;
    private javax.swing.JTextField txthealth;
    private javax.swing.JTextField txtip;
    private javax.swing.JTextField txtlicense;
    private javax.swing.JTextField txtlinkedin;
    private javax.swing.JTextField txtmedical;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtserialnumber;
    private javax.swing.JTextField txtssn;
    private javax.swing.JTextField txttelephone;
    private javax.swing.JTextField txtuniqueid;
    // End of variables declaration//GEN-END:variables
}
