/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Order.FinalOrder;
import Business.Order.Order;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sunny
 */
public class manageOrders extends javax.swing.JPanel {

    /**
     * Creates new form manageOrders
     */
    
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    UserAccount ua;
    Restaurant resto;
    RestaurantDirectory rd;
    CustomerDirectory cd;
    ArrayList<FinalOrder> ordersList;
    DeliveryManDirectory dd;
    public manageOrders(JPanel userProcessContainer,Restaurant resto,EcoSystem ecosystem) {
        this.userProcessContainer = userProcessContainer;
        this.resto = resto;
        this.ecosystem = ecosystem;
        initComponents();
        populatetree();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAvailableOrders = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ordersAvailble = new javax.swing.JTable();
        btnAccept = new javax.swing.JButton();
        lblCurrent = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        statusOrders = new javax.swing.JTable();
        lblAssignDeliveryPerson = new javax.swing.JLabel();
        delDropDown = new javax.swing.JComboBox<>();
        lblOrderId = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        delCusto = new javax.swing.JTextField();
        lblItem = new javax.swing.JLabel();
        delItem = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        delList = new javax.swing.JComboBox<>();
        btnAssignDel = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        bgdimg = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAvailableOrders.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblAvailableOrders.setText("All Available Orders");
        add(lblAvailableOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 260, 50));

        ordersAvailble.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer", "Item", "Date"
            }
        ));
        jScrollPane1.setViewportView(ordersAvailble);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 370, 150));

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, -1, -1));

        lblCurrent.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblCurrent.setForeground(new java.awt.Color(255, 255, 255));
        lblCurrent.setText("Current and Previous Orders");
        add(lblCurrent, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 320, 50));

        statusOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer", "Item", "status", "Delivery", "Comment", "OrderId", "Order date"
            }
        ));
        jScrollPane3.setViewportView(statusOrders);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 369, 540, 120));

        lblAssignDeliveryPerson.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAssignDeliveryPerson.setForeground(new java.awt.Color(255, 255, 255));
        lblAssignDeliveryPerson.setText("Assign Delivery Person");
        add(lblAssignDeliveryPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 240, 32));

        delDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delDropDownActionPerformed(evt);
            }
        });
        add(delDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 590, 100, -1));

        lblOrderId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblOrderId.setForeground(new java.awt.Color(255, 255, 255));
        lblOrderId.setText("OrderId");
        add(lblOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 590, 62, -1));

        lblCustomer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCustomer.setForeground(new java.awt.Color(255, 255, 255));
        lblCustomer.setText("Customer:");
        add(lblCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 630, 70, -1));

        delCusto.setEditable(false);
        delCusto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delCustoActionPerformed(evt);
            }
        });
        add(delCusto, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 630, 100, -1));

        lblItem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblItem.setForeground(new java.awt.Color(255, 255, 255));
        lblItem.setText("Item");
        add(lblItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 630, -1, -1));

        delItem.setEditable(false);
        add(delItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 630, 84, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DeliveryMan");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 670, -1, -1));

        add(delList, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 670, 100, -1));

        btnAssignDel.setText("Assign");
        btnAssignDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignDelActionPerformed(evt);
            }
        });
        add(btnAssignDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 670, -1, -1));

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, -1, -1));

        bgdimg.setForeground(new java.awt.Color(255, 255, 255));
        bgdimg.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        bgdimg.setIcon(new javax.swing.ImageIcon("D:\\Study\\Northeastern University\\INFO 5100_AED\\Assignments\\Assignment Images\\Assignment 5\\waiter_822x716.jpg")); // NOI18N
        add(bgdimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 830, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        
        if(resto.getAcceptedOrders() == null)
            resto.setAcceptedOrders(new ArrayList<FinalOrder>());
        ArrayList<FinalOrder> orders = resto.getAcceptedOrders();
        rd = ecosystem.getRestaurantDirectory();
        int orderId = rd.generateOrderId();
        FinalOrder fo = new FinalOrder();
        DefaultTableModel df = (DefaultTableModel) ordersAvailble.getModel();
        
          int selectedRow = ordersAvailble.getSelectedRow();
          String customer = df.getValueAt(selectedRow,0).toString();
          String item = df.getValueAt(selectedRow, 1).toString();
          String date = df.getValueAt(selectedRow,2).toString();
          fo.setOrderId(String.valueOf(orderId));
          fo.setCustomer(customer);
          fo.setItem(item);
          fo.setDate(date);
          fo.setRestaurant(resto.getName());
          fo.setStatus("Order Accepted");
          orders.add(fo);
          df.removeRow(selectedRow);
          populatetree();
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void delCustoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delCustoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delCustoActionPerformed

    private void delDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delDropDownActionPerformed
        // TODO add your handling code here:
        String orderId =(String) delDropDown.getSelectedItem();
        DefaultComboBoxModel df = new DefaultComboBoxModel();
        rd = ecosystem.getRestaurantDirectory();
        FinalOrder f = rd.getOrder(orderId);
        delCusto.setText(f.getCustomer());
        delItem.setText(f.getItem());
        dd = ecosystem.getDeliveryManDirectory();
        ArrayList<DeliveryMan> deliveryMen = dd.getDeliveryDirectory();
        for(DeliveryMan d: deliveryMen)
        {
            df.addElement(d.getName());
        }
        delList.setModel(df);
    }//GEN-LAST:event_delDropDownActionPerformed

    private void btnAssignDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignDelActionPerformed
        // TODO add your handling code here:
        String orderId =(String) delDropDown.getSelectedItem();
        rd = ecosystem.getRestaurantDirectory();
        FinalOrder f = rd.getOrder(orderId);
        f.setDeliveryMan((String) delList.getSelectedItem());
        f.setStatus("DeliveryMan Assigned");
        populatetree();
        delCusto.setText("");
        delItem.setText("");
    }//GEN-LAST:event_btnAssignDelActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
            crdLyt.show(userProcessContainer,"RestaurantAdmin");
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgdimg;
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnAssignDel;
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField delCusto;
    private javax.swing.JComboBox<String> delDropDown;
    private javax.swing.JTextField delItem;
    private javax.swing.JComboBox<String> delList;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAssignDeliveryPerson;
    private javax.swing.JLabel lblAvailableOrders;
    private javax.swing.JLabel lblCurrent;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblOrderId;
    private javax.swing.JTable ordersAvailble;
    private javax.swing.JTable statusOrders;
    // End of variables declaration//GEN-END:variables

    private void populatetree() {
        String resoName = resto.getName();
        cd = ecosystem.getCustomerDirectory();
        DefaultTableModel dt = (DefaultTableModel) ordersAvailble.getModel();
        dt.setRowCount(0);
        ArrayList<Customer> customers = cd.getCustomerList();
        for(Customer c: customers)
        {
            ArrayList<Order> orders = c.getPreviousOrders();
            for(Order o: orders)
            {
                if(o.getRestaurant().equals(resoName))
                {
                    String[] row = {c.getCustomerName(),o.getItem(),o.getEntryDateTime().toString()};
                    dt.addRow(row);
                }
            }
        }
        
        ordersAvailble.setModel(dt);
        
        ArrayList<FinalOrder> orders = resto.getAcceptedOrders();
        DefaultTableModel df = (DefaultTableModel) statusOrders.getModel();
        DefaultComboBoxModel dc = new DefaultComboBoxModel();
        df.setRowCount(0);
        for(FinalOrder f: orders)
        {
            String[] row = {f.getCustomer(),f.getItem(),f.getStatus(),f.getDeliveryMan(),f.getReview(),f.getOrderId(),f.getDate()};
            df.addRow(row);
            if(f.getDeliveryMan() == null)
            dc.addElement(f.getOrderId());
        }
        
        statusOrders.setModel(df);
        delDropDown.setModel(dc);
        
    }
}
