/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRoles;

import Business.Customer.Customer;
import Business.Customer.CustomerDirectory;
import Business.EcoSystem;
import Business.Order.CartModel;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.createNewUser.createLogin;

/**
 *
 * @author sunny
 */
public class CustomerRestaurantOrder extends javax.swing.JPanel {

    /**
     * Creates new form CustomerRestaurantOrder
     */
        private JPanel userProcessContainer;

     UserAccount userAccount;
    EcoSystem ecosystem;
    RestaurantDirectory rd;
    CustomerDirectory cd;
    public CustomerRestaurantOrder(JPanel userProcessContainer, UserAccount account,EcoSystem ecosystem) {
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.ecosystem = ecosystem;
        if(ecosystem.getCustomerDirectory() == null)
            ecosystem.setCustomerDirectory(new CustomerDirectory());
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        restaurantItems = new javax.swing.JTable();
        addToCart = new javax.swing.JButton();
        proceedToCart = new javax.swing.JButton();
        btnViewProfile = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Serif", 3, 48)); // NOI18N
        jLabel2.setText("Menu");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, -1));

        restaurantItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Restaurant", "Item"
            }
        ));
        jScrollPane1.setViewportView(restaurantItems);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 272, 140));

        addToCart.setBackground(new java.awt.Color(192, 218, 233));
        addToCart.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addToCart.setText("Add to cart");
        addToCart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCartActionPerformed(evt);
            }
        });
        add(addToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 173, 90, 30));

        proceedToCart.setBackground(new java.awt.Color(192, 218, 233));
        proceedToCart.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        proceedToCart.setText("Checkout");
        proceedToCart.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        proceedToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedToCartActionPerformed(evt);
            }
        });
        add(proceedToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 160, 40));

        btnViewProfile.setBackground(new java.awt.Color(192, 218, 233));
        btnViewProfile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnViewProfile.setText("View Profile");
        btnViewProfile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });
        add(btnViewProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 90, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Study\\Northeastern University\\INFO 5100_AED\\Assignments\\Assignment Images\\Assignment 5\\placing-an-order_687x492.jpg")); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 490));
    }// </editor-fold>//GEN-END:initComponents

    private void addToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCartActionPerformed
        // TODO add your handling code here:
        DefaultTableModel df = (DefaultTableModel) restaurantItems.getModel();

            
          int selectedRow = restaurantItems.getSelectedRow();
          //if(selectedRow == null)
           //  JOptionPane.showMessageDialog(this, "No Item Selected"); 
          String resto = df.getValueAt(selectedRow,0).toString();
          String item = df.getValueAt(selectedRow, 1).toString();
          CartModel cm = new CartModel(resto, item);
          
       //   if(ecosystem.getCustomerDirectory() == null)
       //       ecosystem.setCustomerDirectory(new ());
       
       
          cd = ecosystem.getCustomerDirectory();
          
          Customer c = cd.getCustoo(userAccount);
          c.addToCart(cm);
          JOptionPane.showMessageDialog(this, "Added to cart");
          
    }//GEN-LAST:event_addToCartActionPerformed

    private void proceedToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedToCartActionPerformed
        // TODO add your handling code here:
           cd = ecosystem.getCustomerDirectory();
          Customer c = cd.getCustoo(userAccount); 
          Cart cart = new Cart(userProcessContainer,c, ecosystem);
        userProcessContainer.add("cart",cart);
            CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
            crdLyt.show(userProcessContainer,"cart");
    }//GEN-LAST:event_proceedToCartActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        // TODO add your handling code here:
        cd = ecosystem.getCustomerDirectory();
        Customer c = cd.getCustoo(userAccount);
        CustomerProfile cp = new CustomerProfile(userProcessContainer,c,ecosystem);
        userProcessContainer.add("profile",cp);
            CardLayout crdLyt = (CardLayout) userProcessContainer.getLayout();
            crdLyt.show(userProcessContainer,"profile");
        
    }//GEN-LAST:event_btnViewProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addToCart;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton proceedToCart;
    private javax.swing.JTable restaurantItems;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        rd = ecosystem.getRestaurantDirectory();
        ArrayList<Restaurant> restoList = rd.getRestaurantList();
        
        DefaultTableModel dt = (DefaultTableModel) restaurantItems.getModel();
        dt.setRowCount(0);
        for(Restaurant r: restoList)
        {
            if(r.getMenu() == null)
                r.setMenu(new ArrayList<String>());
            ArrayList<String> items = r.getMenu();
            for(String s: items)
            {
                String[] row = {r.getName(),s};
                dt.addRow(row);
            }
        }
        
        restaurantItems.setModel(dt);
        
    }
}
